
services:
  - type: web
    name: healthcare-frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
      - src/**/*.js
      - src/**/*.jsx
      - src/**/*.css
      - public/**/*